models/Colaborador.php
<?php

namespace app\models;

use Yii;
use Da\User\Model\User;
use yii\web\UploadedFile;
use yii\helpers\Url;

/**
 * This is the model class for table "colaborador".
 *
 * @property int $id
 * @property boolean|null $publico Si el perfil fue aprobado para ser publicado
 * @property string|null $temp_password Contraseña que el usuario brinda para
 *   hacer su registro. Luego será guardada en User cuando éste se inicialice.
 * @property string|null $razon_social
 * @property string|null $ciudad
 * @property string|null $dni
 * @property string|null $marca
 * @property string|null $actividad
 * @property string|null $descripcion
 * @property string|null $introduccion
 * @property string|null $correo
 * @property string|null $tel
 * @property int|null $mercado_pago
 * @property string|null $whatsapp
 * @property string|null $facebook
 * @property string|null $instagram
 * @property int|null $usuario_id
 *
 * @property User $usuario
 */
class Colaborador extends \yii\db\ActiveRecord
{

    public $marca_image;
    public $verifyCode;

    const CREATING_SCENARIO = 'creating';
    const DEFAULT_SCENARIO = 'default';
    
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'colaborador';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            
	    [['temp_password'], 'string', 'min' => 5, 'max' => 20,
	     'tooShort' => 'La clave debe tener al menos 5 caracteres.',
	     'tooLong' => 'La clave no debe superar los 20 caracteres.'],
	    ['verifyCode', 'captcha', 'on' => Colaborador::CREATING_SCENARIO],
	    [['temp_password'], 'required', 'on' => colaborador::CREATING_SCENARIO],
	    
	    [['descripcion', 'introduccion'], 'string'],
            [['usuario_id', 'rubro_id'], 'integer'],
	    [['publico', 'mercado_pago'], 'boolean'],
	    [['marca_image'], 'image',
	     'skipOnEmpty' => true,
	     'extensions' => 'png, jpg, jpeg, svg',
	     'message' => 'Sólo se aceptan el formato PNG, JPG, SVG'],
            [['razon_social', 'ciudad', 'dni', 'marca',
	      'actividad', 'tel', 'whatsapp',
	      'facebook', 'instagram'], 'string', 'max' => 255],
	    [['correo'], 'email',
	     'message' => 'El correo tiene un formato inválido'],
	    [['razon_social', 'ciudad', 'dni',
	      'actividad', 'descripcion', 'correo', 'tel',
	      'mercado_pago', 'whatsapp', 'rubro_id',
	    ], 'required',
	     'message' => 'Este campo es obligatorio'],
            [['usuario_id'], 'exist',
	     'skipOnError' => true,
	     'targetClass' => User::className(),
	     'targetAttribute' => ['usuario_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
	    'verifyCode' => 'CAPTCHA',
	    'temp_password' => 'Contraseña de sesión',
	    'publico' => 'Público (aprobado)',
            'id' => 'ID',
            'razon_social' => 'Razón Social',
            'ciudad' => 'Ciudad',
            'dni' => 'DNI',
            'marca' => 'Marca',
            'actividad' => 'Actividad',
            'descripcion' => 'Descripción',
            'introduccion' => 'Introducción',
            'correo' => 'Correo',
            'tel' => 'Tel.',
            'mercado_pago' => 'Mercado Pago',
            'whatsapp' => 'Whatsapp',
            'facebook' => 'Facebook',
            'instagram' => 'Instagram',
            'usuario_id' => 'Usuario ID',
        ];
    }

    /**
     */
    public function getMarca_URL(){
	if ($this->marca != null){
	    return Url::to('@web/upload_marcas/' . $this->marca);
	}else{
	    return Url::to('@web/imgs/cropped-favicon-180x180.png');
	}
    } // getMarcaUrl
    
    /**
     */
    public function upload_marca(){
	if ($this->marca_image == null){
	    $this->marca = null;
	    return true;
	}
	if ($this->validate()){

	    $this->marca = $this->marca_image->baseName . '-' .
			  uniqid() . '.' .
			  $this->marca_image->extension;
	    $filename = '../web/upload_marcas/' . $this->marca;

	    $this->marca_image->saveAs($filename);
	    
	    $this->marca_image = null;
	    return true;
	}else{
	    return false;
	}
    } // upload_marca
    
    /**
     * Gets query for [[Usuario]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsuario()
    {
        return $this->hasOne(User::className(), ['id' => 'usuario_id']);
    }

    /**
     */
    public function getRubro(){
	return $this->hasOne(Rubro::className(), ['id' => 'rubro_id']);
    } // getRubro

    /**
       Asignar las ciudades como aquellas que el colaborador presta servicios.

       @param $lst_ciudades array[string] Un listado de nombres de ciudades.
     */
    public function asignar_ciudades($lst_ciudades){
	if ($lst_ciudades == null){
	    return true;
	}
	$this->unlinkAll('ciudades', true);
	
	foreach ($lst_ciudades as $nombre){
	    $ciudad = Ciudad::find()->where(['id' => $nombre])->one();
	    if ($ciudad != null){
		$this->link('ciudades', $ciudad);
	    }
	}
    } // asignar_ciudades
    
    /**
     */
    public function getCiudades(){
	return $this->hasMany(Ciudad::className(), ['id' => 'ciudad_id'])
	      ->viaTable('colaborador_ciudad', ['colaborador_id' => 'id']);
    } // getCiudades

    /**
     */
    public function getVouchers(){
	return $this->hasMany(Voucher::className(), ['colaborador_id' => 'id']);
    } // getVouchers
    
    /**
       Crear el usuario que corresponde con este colaborador.

       Usar el DNI como su nombre de usuario.
       
       @return False si el usuario ya existe. True si se creó exitósamente.
     */
    public function crear_usuario(){
	$auth =  Yii::$app->authManager;
	
	if ($this->usuario_id != null){
	    return false;
	}

	$usuario = new User();
	$usuario->username = $this->dni;
	$usuario->password = $this->temp_password;
	$usuario->email = $this->correo;
	
	if (!$usuario->save()) {
	    throw new \Exception("Problems creating user for Colaborator");
	}

	// Asignar rol colaborador.
	$colabrole = $auth->getRole('Colaborador');	
	$auth->assign($colabrole, $usuario->id);

	// Usuario creado, asignarlo al colaborador
	$prevScen = $this->getScenario();
	$this->setScenario(Colaborador::DEFAULT_SCENARIO);
	
	$this->usuario_id = $usuario->id;
	if (!$this->save()){
	    throw new \Exception("Problems assigning user to colaborator:" .
				 var_export($this->getErrors(), true));	    
	}

	$this->setScenario($prevScen);
	
	return true;	
    } // crear_usuario

    /**
     */
    public function getFriendly_url(){
	return Url::to(['colaborador/tarjeta',
		  'razon_social' => str_replace(' ', '-', $this->razon_social)], true);
    } // get_friendly_url
    
    /**
     */
    public static function find_by_user($user){
	return Colaborador::find()->where(['usuario_id' => $user->id])->one();
    } // find_by_user

    /**
     */
    public function puede_crear_voucher(){
	return sizeof($this->vouchers) < 5;
    } // puede_crear_voucher


}

controllers/ColaboradorController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Colaborador;
use app\models\ColaboradorSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\UploadedFile;

/**
 * ColaboradorController implements the CRUD actions for Colaborador model.
 */
class ColaboradorController extends Controller
{

    /**
     */
    public function actions(){
	return [
	    'captcha' => [
		'class' => \yii\captcha\CaptchaAction::className(),
	    ]
	];
    } // actions
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
	    ],

	    'access' => [
		'class' => AccessControl::className(),
		'rules' => [
		    [
			'allow' => true,
			'actions' => ['tarjeta', 'create'],
			'roles' => [],
		    ],
		    [
			'allow' => true,
			'actions' => ['tarjeta', 'update', 'create'],
			'roles' => ['colaborador-update', 'colaborador-create'],
		    ],
		    [
			'allow' => true,
			'actions' => ['index', 'view', 
				     'update', 'create', 'delete'],
			'roles' => ['colaborador-management'],
		    ],
		    [
			'allow' => true,
			'actions' => ['publicar'],
			'roles' => ['colaborador-publicar'],
		    ],
	    ]],
        ];
    }

    /**
     * Lists all Colaborador models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ColaboradorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Colaborador model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
	$model = $this->findModel($id);
	
        return $this->render('view', [
	    'model' => $model
        ]);	
    }

    public function actionTarjeta($id=null, $razon_social=null)
    {
	$razon_social = str_replace('_', ' ', $razon_social);
	$razon_social = str_replace('-', ' ', $razon_social);
	
	if ($razon_social != null) {
	    $model = Colaborador::find()
				->where(['razon_social' => $razon_social])
				->one();
	    if ($model == null){
		throw new NotFoundHttpException('The requested page does not exist.');
	    }
	}
	
	if ($id != null){
	    $model = $this->findModel($id);
	}
	
	if ($model->publico || Yii::$app->user->can('colaborador-publicar')){
	    $this->layout = 'tarjeta';
            return $this->render('tarjeta', [
		'model' => $model,
            ]);
	}else{
	    throw new NotFoundHttpException('The requested page does not exist.');
	}
    }

    /**
     * Creates a new Colaborador model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Colaborador(['scenario' => Colaborador::CREATING_SCENARIO]);
	$model->publico = false;

        if ($model->load(Yii::$app->request->post())){

	    // Subir la imagen de la marca
	    $imagen = UploadedFile::getInstance($model, 'marca_image');
	    if ($imagen != null){
		$model->marca_image = $imagen; 
		$model->upload_marca();
	    }

	    // Asignar las ciudades seleccionadas
	    $model->asignar_ciudades(Yii::$app->request->post('ciudades'));
	    
 	    if ($model->save()) {
		// return $this->redirect(['view', 'id' => $model->id]);
		return $this->goHome();
	    }
	}

        return $this->render('create', [
	    'model' => $model,
        ]);
    }

    /**
     * Updates an existing Colaborador model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())){

	    $imagen = UploadedFile::getInstance($model, 'marca_image');
	    if ($imagen != null){
		$model->marca_image = $imagen; 
		$model->upload_marca();
	    }

	    /*
	       if (! Yii::$app->user->can('colaborador_change_user_id')){
	       // Asignarle el usuario_id si no puede cambiarlo (no es Admin)
	       $model->usuario_id = Yii::$app->user->id;
	       }
	     */

	    $model->asignar_ciudades(Yii::$app->request->post('ciudades'));
	    
	    if ($model->save()) {
		return $this->redirect(['tarjeta', 'id' => $model->id]);
	    }

        }

        return $this->render('update', [
	    'model' => $model,
        ]);
    }

    public function actionPublicar($id, $value)
    {
        $model = $this->findModel($id);
	
	// No hace falta chequear permisos porque se hace en behaviours()
	$model->publico = $value;

	if ($model->publico && ($model->usuario_id == null)){
	    // Asignarle el usuario_id si no lo tiene
	    if (!$model->crear_usuario()){
		throw new \Exception("There's a problem creating the card");
	    }
	}
	
	if (!$model->save()){
	    throw new \Exception("There's a problem seting the card public");
	}
	
        return $this->redirect(['view', 'id' => $model->id]);
    }


    /**
     * Deletes an existing Colaborador model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Colaborador model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Colaborador the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Colaborador::findOne($id)) !== null) {
	    return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

}

views/colaborador/_carousel.php
<?php
use yii\bootstrap\Carousel;

use yii\helpers\Html;
use yii\helpers\Url;


$items = [];
foreach ($model->vouchers as $voucher){

    $text = $this->render('_voucher', [
	'model' => $voucher
    ]);
   
    $items[] = [
	// 'content' => Html::img($voucher->foto_URL),
	'content' => $text, 
	// 'caption' => 
    ];
}

?>

  <?= Carousel::widget([
      'items' => $items,
      'showIndicators' => true,
      'options' => [
	  'class' => 'carousel slide'],
      'controls' => [
	  '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
	<span class="sr-only">Anterior</span>',
	  '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
	<span class="sr-only">Siguiente</span>',
      ],
  ]); ?>

views/colaborador/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ColaboradorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="colaborador-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'razon_social') ?>

    <?= $form->field($model, 'ciudad') ?>

    <?= $form->field($model, 'dni') ?>

    <?= $form->field($model, 'marca') ?>

    <?php // echo $form->field($model, 'actividad') ?>

    <?php // echo $form->field($model, 'descripcion') ?>

    <?php // echo $form->field($model, 'introduccion') ?>

    <?php // echo $form->field($model, 'correo') ?>

    <?php // echo $form->field($model, 'tel') ?>

    <?php // echo $form->field($model, 'mercado_pago') ?>

    <?php // echo $form->field($model, 'whatsapp') ?>

    <?php // echo $form->field($model, 'facebook') ?>

    <?php // echo $form->field($model, 'instagram') ?>

    <?php // echo $form->field($model, 'usuario_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/colaborador/_voucher.php
<?php

/* @var $model app\models\Voucher */

use yii\helpers\Html;
use yii\helpers\Url;
use rmrevin\yii\fontawesome\FAR;

?>
<div class="container">
  

  <div class="voucher-outter">
    <div class="voucher-inner">

      <div class="row">
	

	<div class="col-md-6">
	  
	  <?php if  ($model->foto_URL != null){ ?>
	    <?= Html::img($model->foto_URL); ?>
	  <?php } ?>

	</div>

	<div class="col-md-6">
	  <div class="details">
	    <h1 class="subtitle"> <?= $model->servicio ?> </h1>

	    <?php if ($model->con_promo){ ?>
	      <p class="antes"> Antes: <?= $model->precio ?> </p>
	      <p class="precio"> Precio: <?= $model->promo_descuento ?> </p>
	    <?php }else{ ?>
	      <p class="precio">Precio: <?= $model->precio ?> </p>
	    <?php } ?>

	    <p class="desc"> <?= $model->descripcion ?></p>

	    <?= Html::a('COMPRAR ' . FAR::icon('arrow-alt-circle-right'),
		      $model->mercado_pago,
		      ['class' => 'comprar-link']) ?>

	  </div>
	</div>
      </div>
    </div>
  </div>
</div>

views/colaborador/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ColaboradorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

use rmrevin\yii\fontawesome\FAS;

$this->title = 'Tarjetas';
$this->params['breadcrumbs'][] = $this->title;

$buttons = [
    'card' => function ($url, $model, $key) {
        return  Html::a(FAS::icon('id-card'),
		  Url::to(['colaborador/tarjeta', 'id' => $model->id]));
    }
]
?>
<div class="colaborador-index">

  <h1><?= Html::encode($this->title) ?></h1>

  <?php if (Yii::$app->user->can('colaborador-create')) { ?>
    <div class="panel panel-danger">
      <div class="panel-heading">
	<span class="glyphicon glyphicon-fire" />
	Admin
      </div>
      <div class="panel-body">
	<?= Html::a('Create Colaborador', ['create'], ['class' => 'btn btn-success']) ?>
      </div>
    </div>
  <?php } ?>

  <?php Pjax::begin(); ?>
  <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

  <div class="table-responsive">
    
    <?= GridView::widget([
	'dataProvider' => $dataProvider,
	'filterModel' => $searchModel,
	'rowOptions' => function ($model, $index, $widget, $grid) {

            return [
		'id' => $model['id'],
		'onclick' => 'location.href="'
			. Yii::$app->urlManager->createUrl('colaborador/view')
			. '?id="+(this.id);'
            ];
	},
	'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'razon_social',
            // 'marca',
            'actividad',
	    ['attribute' => 'rubro.nombre',
	     'label' => 'Rubro'],
	    'publico:boolean',
            ['attribute' => 'descripcion',
	     'format' => 'ntext',
	     'contentOptions' => [
		 'style' => 'min-width: 400px'
	     ],
	    ],
            ['attribute' => 'introduccion',
	     'format' => 'ntext',
	     'contentOptions' => [
		 'style' => 'min-width: 400px',
	     ],
	    ],
            'correo:email',          
            'mercado_pago:boolean',
            'whatsapp',
            'facebook:url',
            'instagram:url',
	    [ 'attribute' => 'ciudades',
	      'value' => function ($model) {
		  $nombres = [];
		  foreach ($model->ciudades as $ciudad){
		      $nombres[] = $ciudad->nombre;
		  }
		  return join (",", $nombres);
	      }
	    ],

            ['class' => 'yii\grid\ActionColumn',
	     'buttons' => $buttons,
	     'template' => '{card}{view}{update}{delete}'],
	],
    ]); ?>

  </div><!-- .table-responsive -->
  
  <?php Pjax::end(); ?>

</div>

views/colaborador/tarjeta.php
<?php

/* @var $model app\models\Colaborador */

use yii\helpers\Html;
use yii\helpers\Url;

use rmrevin\yii\fontawesome\FAS;
use rmrevin\yii\fontawesome\FAB;
use rmrevin\yii\fontawesome\FAR;

use Da\QrCode\QrCode;

use app\assets\TarjetaAsset;
TarjetaAsset::register($this);

$qrurl = $model->friendly_url;
$qrCode = (new QrCode($qrurl))->setSize(150)->setMargin(5);

$qrCode->writeFile(__DIR__ . '/QRCode.png');
header('Content-Type: ' . $qrCode->getContentType());

?>
<?php
if (Yii::$app->user->can('colaborador-publicar') &&
    !$model->publico){
?>
  <div class="container">
    <div class="alert alert-danger">
      <span class="glyphicon glyphicon-fire" />
      Esta tarjeta no se encuentra aprobada para publicar.
      Usted puede verla por poseer los permisos necesarios.
    </div>
  </div>
<?php } ?>

<div class="header-tarj">
  <div class="container">
    <div class="header-left">
      
      <p class="rubro">
	<?= $model->actividad ?>
      </p>

      <h1 class="razon_social">
	<?= $model->razon_social ?>
      </h1>

      <p class="ciudad">
	<?= $model->ciudad ?>
      </p>
      
    </div>
    <div class="header-right">
      <?= Html::img($model->marca_URL, [
	  'class' => 'img-circle img-marca',
      ]); ?>      
    </div>

  </div>
</div>


<div class="servicios background-2">
  <div class="container">
    <h1 class="subtitle">Servicios</h1>
    <p class="text">
      <?= $model->descripcion ?>
    </p>
  </div>
</div>


<div class="opiniones strip-background">
  <div class="container">
    <h2 class="subtitle">Opiniones</h2>
    <p class="text"></p>
  </div>
</div>

<div class="background-2">
  <div class="container">
    <h2 class="subtitle">Contacto</h2>
    <p class="text contact-text">
      <img draggable="false" role="img" class="emoji" alt="👋"
	   src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f44b.svg"
	   data-src="https://s.w.org/images/core/emoji/12.0.0-1/svg/1f44b.svg">
      ¡Hola! Podés contactarnos por los siguientes medios:
    </p>
    <div class="row contact-buttons">
      <div class="col-xs-2">	
      </div>
      <div class="col-xs-2">
	<?php
	if ($model->whatsapp != "" and $model->whatsapp != null){
	    echo Html::a(FAS::icon('phone'),
			'tel:' . $model->whatsapp,[
			    'class' => 'contact-button'
	    ]);
	} ?>
	
      </div>
      <div class="col-xs-2">
	<?php if ($model->whatsapp != "" and $model->whatsapp != null){
	    echo Html::a(FAB::icon('whatsapp'),
			'https://wa.me/' . $model->whatsapp,[
			    'class' => 'contact-button'
	    ]);
	}?>
      </div>
      <div class="col-xs-2">
	<?php
	if ($model->facebook != "" and $model->facebook != null){
	    echo Html::a(FAB::icon('facebook'),
			$model->facebook,[
			    'class' => 'contact-button'
	    ]);
	}?>	
      </div>
      <div class="col-xs-2">
	<?php if ($model->instagram != "" and $model->instagram != null){
	    Html::a(FAB::icon('instagram'),
		   $model->instagram,[
		       'class' => 'contact-button'
	    ]);
	} ?>
      </div>
      <div class="col-xs-2">
      </div>
    </div>
  </div>
</div>


<div class="voucher strip-background">
  <?= $this->render('_carousel', [
      'model' => $model
  ]); ?>
</div>

<div class="historia background-2">
  <div class="container">
    <h2 class="subtitle">Mi historia</h2>
    <p class="text">
      <?= $model->introduccion ?>
    </p>
  </div>
</div>

<div class="comparti strip-background">
  <div class="container">
    <p class="text">¡Compartí mi tarjeta! 🙂</p>


    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-4 text-center">
	<div class="sharer-outline wp-outline">
	  <span class="sharer-inline wp-inline">
	    <a href="<?=
		     "https://api.whatsapp.com/send?text=*" .
		     $model->razon_social . "| Por Más* " .
		     $model->descripcion . " " .
		     $model->friendly_url
		     ?>"
	       class="nobs-link">
	      <?= FAB::icon('whatsapp') ?>
	    </a>
	  </span>
	</div>
	<div class="sharer-outline fb-outline">
	  <span class="sharer-inline fb-inline">
	    <a href="<?=
		     "https://www.facebook.com/sharer.php?u=" .
		     $model->friendly_url		     
		     ?>"
	       class="nobs-link">
	      <?= FAB::icon('facebook') ?>
	    </a>
	  </span>
	</div>
	<div class="sharer-outline telegram-outline">
	  <span class="sharer-inline telegram-inline">
	    <a href="<?=
		     "https://telegram.me/share/url?url=" .
		     $model->friendly_url .
		     "&text=" .
		     "*" . $model->razon_social . " | Por Más* " 
		     ?>"
	       class="nobs-link">
	      <?= FAB::icon('telegram') ?>
	    </a>
	  </span>
	</div>
	<div class="sharer-outline tweet-outline">
	  <span class="sharer-inline tweet-inline">
	    <a href="<?=
		     "https://twitter.com/intent/tweet?text=" .
		     $model->razon_social . "| Por Más :" .
		     $model->friendly_url
		     ?>"
	       class="nobs-link">
	      <?= FAB::icon('twitter') ?>
	    </a>
	  </span>
	</div>
	<div class="sharer-outline linkedin-outline">
	  <span class="sharer-inline linkedin-inline">
	    <a href="<?=
		     "https://www.linkedin.com/shareArticle?mini=true&url=" .
		     $model->friendly_url .
		     "&title=" .
		     $model->razon_social . "| Por Más" .
		     "&summary=" .
		     $model->descripcion .
		     "&source=" . 
		     $model->friendly_url
		     ?>"
	       class="nobs-link">
	      <?= FAB::icon('linkedin') ?>
	    </a>
	  </span>	  
	</div>
	<div class="sharer-outline email-outline">
	  <span class="sharer-inline email-inline">
	    <a href="<?=
		     "mailto:" .
		     "?subject=" .
		     $model->razon_social . " | Por Más" .
		     "&body=" .
		     $model->razon_social . "\n" .
		     $model->descripcion . "\n\n" .
		     $model->friendly_url
		     ?>"
	       class="nobs-link">
	      <?= FAS::icon('envelope') ?>
	    </a>
	  </span>
	</div>

	<br/>
	<?= Html::img($qrCode->writeDataUri(), [
	    'class' => 'img-rounded img-responsive qr-share',
	])?>
	
      </div>    	
    </div>
    <div class="col-md-4">           
    </div>
  </div>
</div>

<div class="quiero background-2">
  <div class="container">

    <p>
      <?=
      Html::a('¡Quiero mi tarjeta <b>GRATIS</b>! '.
	     FAR::icon('arrow-alt-circle-right'),
	     ['site/index'],
	     ['class' => 'quiero-link']);
      ?>
    </p>
    <p>
      <?=
      Html::a('Informar problema',
	     'https://pormas.org/reportar',
	     ['class' => 'informar-fallo'])
      ?>
    </p>
  </div>
</div>